function df_dx = df_dx(in1)
%DF_DX
%    DF_DX = DF_DX(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    28-Aug-2021 18:20:26

x3 = in1(3,:);
x4 = in1(4,:);
x5 = in1(5,:);
x6 = in1(6,:);
t2 = cos(x3);
t3 = sin(x3);
df_dx = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...
    -t2.*x5-t3.*x4,t2.*x4-t3.*x5,0.0,t2.*(-9.81e+2./1.0e+2),t3.*(9.81e+2./1.0e+2),...
    0.0,t2,t3,0.0,0.0,-x6,0.0,-t3,t2,0.0,x6,0.0,0.0,0.0,0.0,1.0,x5,-x4,0.0],[6,6]);
